config/routes.rb
IvyswapApp::Application.routes.draw do

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about' 

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products
  resources :uploads
  

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  image_url   :string(255)
#  price       :decimal(8, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title, :category_name

  belongs_to :user
  belongs_to :category


  #has_one :upload, dependent: destroy

  validates :description, presence: true, length: { maximum: 500 }
  validates :user_id, presence:true
  #validates :category_id, presence:true

  default_scope order: 'products.created_at DESC'
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end

#    @buyer = User.find(current_user.id)
    @seller = User.find(@product.user_id)
    
    Notifier.contact(current_user, @seller).deliver


  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }

      redirect_to root_path
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(params[:product])

    p params
    #respond_to do |format|

      if @product.save
        #format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        #format.json { render :json => @product, :status => :created, :location => @product }
        flash[:success] = "You posted #{@product.title}!"
        redirect_to root_url
      else
        @feed_items = []
        #format.html { render :action => "new" }
        #format.json { render :json => @product.errors, :status => :unprocessable_entity }
        flash[:error] = "Your item must have a description."
        redirect_to root_url
      end

    #end

  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
   
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
    #redirect_to current_user
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to current_user
    #respond_to do |format|
      #format.html { redirect_to @user }
    #end

  end

end

app/helpers/products_helper.rb
module ProductsHelper

	def current
		self.product_category_name
	end

end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@product.errors.count, "error") %>
		prohibited this product from being saved:</h2>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<div class="field">
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</div>
<div class="field">
<%= f.label :description %><br />
<%= f.text_area :description, rows: 6 %>
</div>
<div class="field">
<%= f.label :image_url %><br />
<%= f.text_field :image_url %>
</div>

<div class="field">
<%= f.label :price %><br />
<%= f.text_field :price %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/products/_product.html.erb
    <div class="products"> 
     <table>
    
     <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    
        <td>
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>
    
    
        <td class="list_description">
          <dl>
             <dt><%= product.title %></dt>
             <dt><%= product.price %></dt>
             
             
             <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
          </dl>
        </td>
    
        <td class="list_actions">
          <%= link_to 'Edit', edit_product_path(product) %><br/>
          <%= link_to 'Delete', product, confirm: 'Are you sure?', method: :delete %>
        </td>
      </tr>
      
  </table>
    </div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>


<%= link_to 'Back', current_user %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<div class="products">
  <table>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    
    
        <td>
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>
    
    
        <td class="list_description">
          <dl>
             <dt><%= product.title %></dt>
             <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
          </dl>
        </td>
    
        <td class="list_actions">
          <%= link_to 'Show', product %><br/>
          <%= link_to 'Edit', edit_product_path(product) %><br/>
          <%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %>
    
        </td>
      </tr>
    <% end %>
  </table>

</div>

<br />

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', current_user %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', current_user %>