config/routes.rb
IvyswapApp::Application.routes.draw do

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about' 

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products
  resources :uploads
  

end

app/views/layouts/_header.html.erb
<header class="  navbar navbar-fixed-top navbar-inverse  navbar-color">
  <div class="navbar-inner">
    <div class="container">
    	<%= link_to "Cx", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "All Listings", root_path %></li>
            <li><%= link_to "Your Listings", current_user %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name.capitalize %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CX - Columbia Exchange | <%= yield(:title) %></title>
      <%= stylesheet_link_tag "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
  </head>
  <body class='<% controller.controller_name %>'>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>

  </body>

  
</html>